### ISSUE TITLE
`serde` feature is not available

### ISSUE THREAD

**Issue by WesleyAC** [feed-rs/feed-rs#142]
The code seems to [expect a serde feature flag](https://github.com/feed-rs/feed-rs/blob/5f38edbb0ef6f0a05621f9a5c5c513dd1c1012e6/feed-rs/src/model.rs#L37), but this does not exist in `Cargo.toml`. Could this feature be declared in `Cargo.toml` so it can be used?

Thanks!

**Comment by WesleyAC** [comment]
I get this error when trying to use the feature:

```
error: failed to select a version for `feed-rs`.
    ... required by package `reader v0.0.0 (/home/wesleyac/code/reader)`
versions that meet the requirements `^1.0` are: 1.0.0

the package `reader` depends on `feed-rs`, with features: `serde` but `feed-rs` does not have these features.
 It has a required dependency with that name, but only optional dependencies can be used as features.


failed to select a version for `feed-rs` which could resolve this conflict
```

**Comment by WesleyAC** [comment]
76e3beec5d66ec40a655cc6299d8c4cd280adcc9 is a commit that adds this, if you want to pull it in, although it does rely on a unreleased version of `mime`.

**Comment by markpritchard** [comment]
Thanks @WesleyAC , I'll clean this up by removing support for it as a feature (since its non-optional now, doesn't really make sense).

**Comment by ndelvalle** [comment]
@markpritchard what would you recommend as a best practice to ser/de these public structs? Should we create a wrapper type and implement ser/de for this wrapper? Or is there a better way?

**Comment by ndelvalle** [comment]
> The code seems to [expect a serde feature flag](https://github.com/feed-rs/feed-rs/blob/5f38edbb0ef6f0a05621f9a5c5c513dd1c1012e6/feed-rs/src/model.rs#L37), but this does not exist in `Cargo.toml`. Could this feature be declared in `Cargo.toml` so it can be used?
> 
> Thanks!

I think having this feature was a good idea, can we consider bringing it back? I can do a PR if you guys think it is a good idea.

**Comment by liebkne** [comment]
Why was it removed?

**Comment by markpritchard** [comment]
It was a feature when I inherited the crate as maintainer, but didn't appear widely used.

The challenge with serialisation is backward compatibility. I'm not convinced `feed-rs` should carry that maintenance overhead.

**Comment by markpritchard** [comment]
Sorry @ndelvalle , I didn't see your comments on this ticket. It would be interesting to understand the use cases.

**Comment by ndelvalle** [comment]
Hi @markpritchard, If I remember correctly I think I wanted to insert one of the public struct into a database. The database library had a serde trait bound to insert the document. Because some of the public struct are pretty big is convenient to use those directly instad of having an own representation of the same data on my code that implements serde.

What do you mean by:
>The challenge with serialisation is backward compatibility. I'm not convinced feed-rs should carry that maintenance overhead.

The struct that were using serde were public so the backward compatibility issue already exists?

**Comment by liebkne** [comment]
Without that feature one would need to create every wrapper struct for the pub structs in the crate for serializing to most common data types due to the orphan rule.

**Comment by markpritchard** [comment]
> > The challenge with serialisation is backward compatibility. I'm not convinced feed-rs should carry that maintenance overhead.
> 
> The struct that were using serde were public so the backward compatibility issue already exists?

The `serde` feature was active back when `feed-rs` had very limited usage and didn't have the object model it has in place now. So it existed for a brief time, but not really in this flavour of the create.

The backward compatibility issue is if there is incompatible changes to the model (e.g. a field rename or removal, or making a field optional) then deserialisation of the model will fail unless `feed-rs` can handle that change and do something sensible (default data, `None` for an `Option` etc).

Not a new problem, but backward compatible serialisation/deserialisation is something that costs a lot of time in my day job so I'm wary of introducing this into `feed-rs` without careful consideration.

The model is fairly stable these days (it changed rapidly as I added support for new feed types and additional schemas such as the MediaRSS spec). It seems like there is interest so it would be good to understand the use cases further.

**Comment by markpritchard** [comment]
> Without that feature one would need to create every wrapper struct for the pub structs in the crate for serializing to most common data types due to the orphan rule.

Yes, that is the symptom of not having `serde` support. But doesn't address the issues with implementing it (backward compatible serialisation/deserialisation).

It would be good to understand the use cases behind serialisation - e.g. storing the parsed objects in a database would infer they have a long life time, so potentially `feed-rs` needs to support the current model for the forseeable future.

In other languages, the serialisation story is quite good e.g. if a field is renamed you can change the accessor function to return something sensible and uses of the library continue to compile. 

A contrived example, if I had a `Person` and it had an `age()` function that returned an int we could imagine replacing the integer age field with a date of birth and computing `age()` on the fly. With Rust, users of the crate access `Person.age` directly. 

This field would need to remain, and be computed on the fly post deserialisation but prior to returning reconstructed object graph to the user of the crate.

Again, none of these are blocking issues ... just extra work for the crate maintainer (i.e. me :) )

**Comment by markpritchard** [comment]
> @markpritchard if we change a struct and we remove or update an attribute, I think that is a breaking change regardless if we have serde
Not necessarily - a field such as `Image.description` is optional. If `feed-rs` stopped deserialising this (no idea why, just a contrived example), then its just `None`. Your code continues to compile, and you had to handle this enum discriminent anyway. Or, we could imagine `Image` gains a `body` to unify the names with ither entities - we'd have to populate that with other content.

The point is that these cases are context dependent - what is important to my use of the library may or may not be important to you.

Serialisation (and deserialisation with versioning) is a difficult problem to get right. There are problems with native Java serialisation, the Jackson JSON libraries and the annotations to control parsing flow, the many cross language alternatives such as MessagePack, Avro, flatbuffers, protobuf etc. Versioning and persistence is not a simple problem, particularly for a library (crate) author since I don't control your code.

>  if the user is storing the data on the database maybe it needs a migration?
At work we have ~3Tb of JSON serialised data spanning ~6 years. We are on version 5 of the schema now. We don't migrate this, rather we version the content and transparently update it on retrieval. I'm thinking of this approach if we added serde back to feed-rs.

> What would be the current procedure if there is a need to remove or add a new attribute on a public struct without taking into account serde?
Adding a new attribute is free - it doesn't break your code.
Removing an attribute would be a major version bump since your code wont compile.

**Comment by markpritchard** [comment]
As I mentioned earlier, it would be good to understand the use cases for serialisation.
e.g. 
* persistent store ... writing to a database across separate tables? writing to files?
* level at which you serialise (Feed? Entry? lower?)
* do you expect feed-rs to transparently handle deserialisation changes? Or would you implement a serde deserialisation handler? Or transform it yourself before giving it to serde? (I don't seriously expect people to do this themselves, feels like you'd want the crate to do this)

Understanding use cases for those advocating for the feature would help design it.

**Comment by markpritchard** [comment]
Just following up open issues, I'm wondering if serialising the original JSON works here? As feed-rs improves parsing etc, having the original JSON means future parsing is not lossy.

**Comment by maheshbansod** [comment]
My use case is to return `Feed` from [create_resource in leptos](https://leptos-rs.github.io/leptos/async/10_resources.html) .. currently i can think of two solution to work around this:
by either creating a wrapping type, or maybe some weird solution with a derived signal (that depends on the resource which would be the unparsed string).
(though i'll probably go with a wrapper type for now)
Has anyone else did something like this?/Is there a recommended way for this?

**Comment by zeerooth** [comment]
If anyone else is struggling with using serde with this crate, here are the serde docs on how to do this (it basically involves copying over the struct from remote crate, which is feed_rs in this case ofc, and using certain serde attributes):
https://serde.rs/remote-derive.html

I don't see though why we can't have a serde feature here in feed_rs. Even if there are breaking changes when it comes to struct fields, serde provides attributes that could help mitigate that with either renaming the fields for de/serialization, providing defaults, skipping de/serialization of a certain field etc. Borderline just make a major version change noting the breaking change in the changelog.

As for my use case, I have to deal both with XML and JSON + keeping the original format would be quite inefficient as I'm using an embedded DB unlike PostgreSQL with it's amazing json support.

**Comment by markpritchard** [comment]
> I don't see though why we can't have a serde feature here in feed_rs. 

@zeerooth I've never stated we can't have the serde feature. I have explained why it was removed (a legacy feature inherited from a time when this crate was unmaintained and I took it over).

And I also asked back in July 2023 for some more details on use cases so I could understand how people expected to use it and make any upgrade or transition paths easier. Since then, I've received just two responses other than yours today.

For a feature in such high demand, I don't see a) much activity in this ticket nor b) much dialog on helping define the design.

> Borderline just make a major version change noting the breaking change in the changelog.

I've never worked on a system where breaking deserialisation, even between major versions, was acceptable. feed-rs wont break deserialisation between major versions.

I had planned on adding it in the next major release (v2), but there is no ETA for this.
If your struggles prove insurmountable, you can always fork the repo.

**Comment by zeerooth** [comment]
Thanks for the reply,

> And I also asked back in July 2023 for some more details on use cases so I could understand how people expected to use it and make any upgrade or transition paths easier. Since then, I've received just two responses other than yours today.

> For a feature in such high demand, I don't see a) much activity in this ticket nor b) much dialog on helping define the design.

Indeed there doesn't seem to be a lot of activity for this issue, but I think it's because this this crate is already a bit niche and there are certainly ways to circumvent the lack of `serde` derives, either with what I linked or by making your own structs.

Therefore I understand why you might be reluctant to support it, however I can volunteer to make a PR and help or possibly maintain the feature in the future, because I feel like having `serde` support in a crate that deals with parsing data and putting it into models is kind of a must have in the <current year>

> I've never worked on a system where breaking deserialisation, even between major versions, was acceptable. feed-rs wont break deserialisation between major versions.

I'm also not aware of any crates that do break de/serialization actually. Usually you can do with serde renames, defaults and custom de/serialization as I mentioned before. However if you do intent of making a v2 `feed-rs`, which sorry I didn't know about, then adding it now wouldn't be the best option indeed, if you already have plans to break it.

I'm aware that one can make forks, but if possible it's better to have this upstream and I'm always willing to contribute if of course there's any will from the maintainers to have it accepted.

**Comment by markpritchard** [comment]
I'll leave this issue open for now to collect feedback before merging it into 2.0.0 and releasing.

I'm not entirely sure I've prepared a pre-release properly, but you should be able to find `2.0.0-beta.0` in crates.io now.
Please take a look, and let me know if any problems.

Note that there is a breaking change in the model - the `mime` crate is no longer maintained, and doesn't support serialisation. 2.0 switches to `mediatype`.

**Comment by markpritchard** [comment]
v2.0.0 is now out, so closing this issue.
