### ISSUE TITLE
Incorrect extraction of text data when `CDATA` literal is preceded by newline

### ISSUE THREAD

**Issue by daniel-ferguson** [feed-rs/feed-rs#163]
For example, with this podcast: http://feeds.nightvalepresents.com/welcometonightvalepodcast

The description field looks like this:

```
<description>
  <![CDATA[<p>Twice-monthly community updates for ...</p>]]>
</description>
```

And `feed-rs` extracts it as:

```
Text { content_type: "text/plain", src: None, content: "\n      " }
```

I did a little investigation and it looks like description elements are ultimately handled by the following code https://github.com/feed-rs/feed-rs/blob/4c853312148b0aeb83a3f8745abb84c16c9c0216/feed-rs/src/xml/mod.rs#L163-L176

My guess is that `quick-xml` is emitting an `Event::Text` for the whitespace preceding the `CDATA` literal, then an `Event::CData` for text data within it, then another `Event::Text` afterwards. 

I don't have a good understanding of XML, or expectations about what parsers should produce - do you have any thoughts on the following options:

* `quick-xml` emitting multiple events in this scenario is sensible, a change could be made to `feed-rs`
* `quick-xml` emitting multiple events in this scenario is not sensible, I can open an issue there instead
* the XML itself in that feed is somehow non-compliant
* I've completely misunderstood the issue

**Comment by markpritchard** [comment]
Thanks for the bug report @daniel-ferguson , appreciate all the detail.

feed-rs can be opinionated when it parses feeds as the goal was to simplify things for crate users. There are cases where we break rendering by dropping extraneous (according to XML rules) whitespace because of embedded HTML content e.g. "the quick <b>brown</b> fox" needs the whitespace retained surrounding the elements.

In this case, it feels like the whitespace surrounding the `CDATA` is irrelevant so we could trim it.

I'll have a poke around and see what we can do.

**Comment by daniel-ferguson** [comment]
Ok, that makes sense. If you're open to a PR, let me know and I'll find a little time to give this a go.
